### ISSUE TITLE
Errors in browser console

### ISSUE THREAD

**Issue by anup4ranium** [alexgibson/notify.js#63]
Hi Alex ,

Thanks for creating excellent notify.js library .
Unfortunately I am getting issues while trying to use this library sample example on my local machine .

notify.js:32 Uncaught SyntaxError: Unexpected token ...
notify.js:178 Uncaught SyntaxError: Unexpected token export

Also please find attached debug file, which got populated while installing dependencies & build file.

[npm-debug.log.zip](https://github.com/alexgibson/notify.js/files/280970/npm-debug.log.zip)

**Comment by alexgibson** [comment]
Can you please explain what you are doing to encounter this error? It sounds like you are trying to use the ES6 version directly looking at the error?

You need to make sure you have the dependencies installed and transpile to ES5.

Also, you may want to use the current release version instead of using what's currently in master.

**Comment by alexgibson** [comment]
I added a more prominent "Build" section to the README, hope this helps? https://github.com/alexgibson/notify.js/blob/master/README.md#build

**Comment by anup4ranium** [comment]
Hi @alexgibson  , 
Thanks for the reply. 
This is working with downloading latest release in this repo now.
